Sentence Embedding

In [1]:
!pip install -U sentence-transformers

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 156.5/156.5 kB 2.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.7/23.7 MB 29.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 823.6/823.6 kB 37.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.1/14.1 MB 55.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 731.7/731.7 MB 1.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.6/410.6 MB 2.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 121.6/121.6 MB 8.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.5/56.5 MB 10.6 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 124.2/124.2 MB 8.1 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.0/196.0 MB 5.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 166.0/166.0 MB 6.2 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.1/99.1 kB 13.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━

In [2]:
from sentence_transformers import SentenceTransformer,util
model = SentenceTransformer('all-MiniLM-L6-v2')

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [3]:
sentences = ['This framework generates embeddings for each input sentence',
    'Sentences are passed as a list of string.']

embeddings = model.encode(sentences)

for sentence,embedding in zip(sentences,embeddings):
  print(sentence)
  print(embedding)



This framework generates embeddings for each input sentence
[-1.37173338e-02 -4.28515300e-02 -1.56286079e-02  1.40537489e-02
  3.95537764e-02  1.21796295e-01  2.94334106e-02 -3.17524225e-02
  3.54959629e-02 -7.93139786e-02  1.75878834e-02 -4.04370017e-02
  4.97259051e-02  2.54912414e-02 -7.18700439e-02  8.14969167e-02
  1.47071737e-03  4.79627103e-02 -4.50336374e-02 -9.92174968e-02
 -2.81769596e-02  6.45046607e-02  4.44670618e-02 -4.76216935e-02
 -3.52952406e-02  4.38671671e-02 -5.28565869e-02  4.33066773e-04
  1.01921484e-01  1.64072216e-02  3.26996297e-02 -3.45986709e-02
  1.21339019e-02  7.94870928e-02  4.58344584e-03  1.57778431e-02
 -9.68207046e-03  2.87625995e-02 -5.05806319e-02 -1.55793484e-02
 -2.87906323e-02 -9.62281786e-03  3.15556750e-02  2.27348618e-02
  8.71449336e-02 -3.85027491e-02 -8.84718522e-02 -8.75501335e-03
 -2.12343000e-02  2.08923332e-02 -9.02077407e-02 -5.25732227e-02
 -1.05639081e-02  2.88310777e-02 -1.61454733e-02  6.17837440e-03
 -1.23234363e-02 -1.07337218e-

Cosine Similarity

In [4]:
emb1 = model.encode("I am eating a delicious Apple")
emb2 = model.encode("I am working on apple computer")
emb3 = model.encode('I am eating a fruit')
cos_sim = util.cos_sim(emb1,emb2)
print("Cosine Similarity:",cos_sim)
print("Cosine Similarity:",util.cos_sim(emb1,emb3))

Cosine Similarity: tensor([[0.4525]])
Cosine Similarity: tensor([[0.7764]])


Compute cosine similarity between all pairs

In [5]:
sentences = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'The girl is carrying a baby.',
          'A man is riding a horse.',

          'Two men pushed carts through the woods.',
          'A man is riding white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in gorilla costume is playing a set of drums.'
          ]
embeddings = model.encode(sentences)

count=0
for sentence, embedding in zip(sentences,embeddings):
  print(sentence)
  print(embedding)
  count+=1
  if count ==2:
    break



A man is eating food.
[ 3.32415812e-02  4.40608943e-03 -6.27701962e-03  4.83787358e-02
 -1.38702273e-01 -3.36174294e-02  1.01128317e-01 -5.43849580e-02
 -4.32477668e-02 -3.99410948e-02  7.78631913e-03 -1.27488943e-02
 -6.68302253e-02 -1.73865985e-02  4.74505872e-02 -5.77242821e-02
  1.01888381e-01 -9.11651587e-04  8.22614729e-02 -5.03415577e-02
  6.77303076e-02  4.08765152e-02 -3.58018391e-02 -1.00682430e-01
 -6.69358438e-03 -5.31685986e-02  1.00335173e-01 -5.46136312e-02
 -2.28481628e-02  1.38387065e-02  7.48658180e-02 -6.17880225e-02
  6.39215782e-02  1.62387230e-02 -5.32299690e-02 -3.86083722e-02
  3.15276198e-02 -8.11530128e-02 -3.31432149e-02 -5.38532506e-04
 -3.96069884e-03 -1.52734034e-02 -9.86389932e-04  9.57987979e-02
 -5.42920232e-02  1.84572078e-02 -1.07143648e-01  1.38885034e-02
  3.94072905e-02 -2.69243419e-02 -9.15988833e-02 -1.14195300e-02
  3.38137001e-02 -2.58435383e-02  6.42616525e-02  1.21140936e-02
  2.17769854e-02  9.14833248e-02 -1.05038397e-01 -2.19194647e-02
  3

In [6]:
#compute cosine similarity
cos_sim = util.cos_sim(embeddings,embeddings)

print(cos_sim)

tensor([[ 1.0000,  0.7553, -0.1050,  0.2474, -0.0333,  0.1772,  0.0476,  0.0586],
        [ 0.7553,  1.0000, -0.0610,  0.1442, -0.0216,  0.1152,  0.0362,  0.0166],
        [-0.1050, -0.0610,  1.0000, -0.1088, -0.0413, -0.0891,  0.0231,  0.0260],
        [ 0.2474,  0.1442, -0.1088,  1.0000,  0.0362,  0.7362,  0.0821,  0.1379],
        [-0.0333, -0.0216, -0.0413,  0.0362,  1.0000,  0.0745, -0.0380, -0.0902],
        [ 0.1772,  0.1152, -0.0891,  0.7362,  0.0745,  1.0000,  0.0493,  0.1238],
        [ 0.0476,  0.0362,  0.0231,  0.0821, -0.0380,  0.0493,  1.0000,  0.6524],
        [ 0.0586,  0.0166,  0.0260,  0.1379, -0.0902,  0.1238,  0.6524,  1.0000]])


In [7]:
#Print cosine combinations

cos_sim_combo = []
for i in range(len(cos_sim)-1):
  for j in range(i+1,len(cos_sim)):
    cos_sim_combo.append((cos_sim[i][j],i,j))
cos_sim_combo


[(tensor(0.7553), 0, 1),
 (tensor(-0.1050), 0, 2),
 (tensor(0.2474), 0, 3),
 (tensor(-0.0333), 0, 4),
 (tensor(0.1772), 0, 5),
 (tensor(0.0476), 0, 6),
 (tensor(0.0586), 0, 7),
 (tensor(-0.0610), 1, 2),
 (tensor(0.1442), 1, 3),
 (tensor(-0.0216), 1, 4),
 (tensor(0.1152), 1, 5),
 (tensor(0.0362), 1, 6),
 (tensor(0.0166), 1, 7),
 (tensor(-0.1088), 2, 3),
 (tensor(-0.0413), 2, 4),
 (tensor(-0.0891), 2, 5),
 (tensor(0.0231), 2, 6),
 (tensor(0.0260), 2, 7),
 (tensor(0.0362), 3, 4),
 (tensor(0.7362), 3, 5),
 (tensor(0.0821), 3, 6),
 (tensor(0.1379), 3, 7),
 (tensor(0.0745), 4, 5),
 (tensor(-0.0380), 4, 6),
 (tensor(-0.0902), 4, 7),
 (tensor(0.0493), 5, 6),
 (tensor(0.1238), 5, 7),
 (tensor(0.6524), 6, 7)]

In [8]:
all_sentence_combinations=sorted(cos_sim_combo,key=lambda x: x[0],reverse = True)

In [9]:
for score, i, j in all_sentence_combinations[0:5]:
    print(sentences[i],'______', sentences[j],'______', cos_sim[i][j])

A man is eating food. ______ A man is eating a piece of bread. ______ tensor(0.7553)
A man is riding a horse. ______ A man is riding white horse on an enclosed ground. ______ tensor(0.7362)
A monkey is playing drums. ______ Someone in gorilla costume is playing a set of drums. ______ tensor(0.6524)
A man is eating food. ______ A man is riding a horse. ______ tensor(0.2474)
A man is eating food. ______ A man is riding white horse on an enclosed ground. ______ tensor(0.1772)


Semantic Search

In [10]:
from sentence_transformers import SentenceTransformer
model = SentenceTransformer('clips/mfaq')


modules.json:   0%|          | 0.00/229 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/117 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/3.74k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/778 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/configuration_utils.py:365: UserWarning: Passing `gradient_checkpointing` to a config initialization is deprecated and will be removed in v5 Transformers. Using `model.gradient_checkpointing_enable()` instead, or if you are using the `Trainer` API, pass `gradient_checkpointing=True` in your `TrainingArguments`.
  warnings.warn(


pytorch_model.bin:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/464 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.08M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/294 [00:00<?, ?B/s]

1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

[[-4.6362469e-01 -5.6315494e-01 -5.6998533e-01 ... -5.1775336e-02
   1.3976237e-01  2.2713207e-02]
 [-1.7453563e-01  3.0085724e-03 -1.1692224e-01 ... -2.8381208e-01
  -3.3590764e-02 -1.5095185e-01]
 [-9.0509936e-02 -2.6595902e-02 -2.8766245e-01 ... -4.1669866e-01
  -3.9775349e-04 -7.4016489e-02]
 [-9.0509936e-02 -2.6595902e-02 -2.8766245e-01 ... -4.1669866e-01
  -3.9775349e-04 -7.4016489e-02]]


In [16]:
question = "<Q>How many hours do I need to work in office?"
answer_1 = "<A>According to the office HR policy, employee needs to work for 8 hours."
answer_2 = "<A>Not sure about this one"
answer_3 = "<A>Suresh mentioend he works for 10 hrs some times and some times 5 hours"

que_embedding = model.encode(question)
ans_embedding = model.encode([answer_1, answer_3, answer_3])
print(util.semantic_search(que_embedding,ans_embedding))

[[{'corpus_id': 0, 'score': 0.6381703615188599}, {'corpus_id': 1, 'score': 0.6133564114570618}, {'corpus_id': 2, 'score': 0.6133564114570618}]]


In [15]:
from transformers import pipeline

In [17]:
qa_model = pipeline("question-answering")
question = "How many hours do I need to work in office?"
context = "According to the office HR policy, employee needs to work for 8 hours."
qa_model(question = question, context = context)


No model was supplied, defaulted to distilbert/distilbert-base-cased-distilled-squad and revision 626af31 (https://huggingface.co/distilbert/distilbert-base-cased-distilled-squad).
Using a pipeline without specifying a model name and revision in production is not recommended.


config.json:   0%|          | 0.00/473 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/261M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/29.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/213k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/436k [00:00<?, ?B/s]

{'score': 0.6740318536758423, 'start': 62, 'end': 63, 'answer': '8'}

Clustering

In [19]:
from sklearn.cluster import KMeans
import numpy as np

embedder = SentenceTransformer('all-MiniLM-L6-v2')

# Corpus with example sentences
corpus = ['A man is eating food.',
          'A man is eating a piece of bread.',
          'Horse is eating grass.',
          'A man is eating pasta.',
          'A Woman is eating Biryani.',
          'The girl is carrying a baby.',
          'The baby is carried by the woman',
          'A man is riding a horse.',
          'A man is riding a white horse on an enclosed ground.',
          'A monkey is playing drums.',
          'Someone in a gorilla costume is playing a set of drums.',
          'A cheetah is running behind its prey.',
          'A cheetah chases prey on across a field.',
          'The cheetah is chasing a man who is riding the horse.',
          'man and women with their baby are watching cheetah in zoo'
          ]

corpus_embeddings = embedder.encode(corpus)

In [20]:
corpus_embeddings[0]

array([ 3.32415812e-02,  4.40608943e-03, -6.27701962e-03,  4.83787358e-02,
       -1.38702273e-01, -3.36174294e-02,  1.01128317e-01, -5.43849580e-02,
       -4.32477668e-02, -3.99410948e-02,  7.78631913e-03, -1.27488943e-02,
       -6.68302253e-02, -1.73865985e-02,  4.74505872e-02, -5.77242821e-02,
        1.01888381e-01, -9.11651587e-04,  8.22614729e-02, -5.03415577e-02,
        6.77303076e-02,  4.08765152e-02, -3.58018391e-02, -1.00682430e-01,
       -6.69358438e-03, -5.31685986e-02,  1.00335173e-01, -5.46136312e-02,
       -2.28481628e-02,  1.38387065e-02,  7.48658180e-02, -6.17880225e-02,
        6.39215782e-02,  1.62387230e-02, -5.32299690e-02, -3.86083722e-02,
        3.15276198e-02, -8.11530128e-02, -3.31432149e-02, -5.38532506e-04,
       -3.96069884e-03, -1.52734034e-02, -9.86389932e-04,  9.57987979e-02,
       -5.42920232e-02,  1.84572078e-02, -1.07143648e-01,  1.38885034e-02,
        3.94072905e-02, -2.69243419e-02, -9.15988833e-02, -1.14195300e-02,
        3.38137001e-02, -

In [22]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
corpus_emb_scaled = scaler.fit_transform(corpus_embeddings)
corpus_emb_scaled

array([[0.83812165, 0.38709456, 0.55953765, ..., 0.8940437 , 0.18382621,
        0.03472129],
       [0.9857027 , 0.6997658 , 0.5256443 , ..., 0.19780445, 0.        ,
        0.        ],
       [0.51787215, 0.47081748, 1.        , ..., 0.88424844, 0.3500013 ,
        0.09646079],
       ...,
       [0.99999994, 0.69200194, 0.57746184, ..., 0.5948851 , 0.42344305,
        1.        ],
       [0.5711837 , 0.6554799 , 0.6741865 , ..., 0.31139448, 0.7904142 ,
        0.6991767 ],
       [0.82029426, 0.4137553 , 0.18679717, ..., 0.7102249 , 0.49359757,
        0.32150894]], dtype=float32)

In [23]:
clustering_model = KMeans(n_clusters=4)
clustering_model.fit(corpus_embeddings)
cluster_assignment = clustering_model.labels_
print(cluster_assignment)

/usr/local/lib/python3.10/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


[0 0 2 0 0 1 1 2 2 3 3 2 2 2 1]


In [33]:
clustered_sentences = {}
for sentence_id, cluster_id in enumerate(cluster_assignment):

    if cluster_id not in clustered_sentences:
        clustered_sentences[cluster_id] = []

    clustered_sentences[cluster_id].append(corpus[sentence_id])

clustered_sentences

{0: ['A man is eating food.',
  'A man is eating a piece of bread.',
  'A man is eating pasta.',
  'A Woman is eating Biryani.'],
 2: ['Horse is eating grass.',
  'A man is riding a horse.',
  'A man is riding a white horse on an enclosed ground.',
  'A cheetah is running behind its prey.',
  'A cheetah chases prey on across a field.',
  'The cheetah is chasing a man who is riding the horse.'],
 1: ['The girl is carrying a baby.',
  'The baby is carried by the woman',
  'man and women with their baby are watching cheetah in zoo'],
 3: ['A monkey is playing drums.',
  'Someone in a gorilla costume is playing a set of drums.']}